
# Atari-57 taken from Table H.4 of https://arxiv.org/pdf/2003.13350 (Agent57 paper)
ATARI_57 = [
    'Alien',
    'Amidar',
    'Assault',
    'Asterix',
    'Asteroids',
    'Atlantis',
    'BankHeist',
    'BattleZone',
    'BeamRider',
    'Berzerk',
    'Bowling',
    'Boxing',
    'Breakout',
    'Centipede',
    'ChopperCommand',
    'CrazyClimber',
    'Defender',
    'DemonAttack',
    'DoubleDunk',
    'Enduro',
    'FishingDerby',
    'Freeway',
    'Frostbite',
    'Gopher',
    'Gravitar',
    'Hero',
    'IceHockey',
    'Jamesbond',
    'Kangaroo',
    'Krull',
    'KungFuMaster',
    'MontezumaRevenge',
    'MsPacman',
    'NameThisGame',
    'Phoenix',
    'Pitfall',
    'Pong',
    'PrivateEye',
    'Qbert',
    'Riverraid',
    'RoadRunner',
    'Robotank',
    'Seaquest',
    'Skiing',
    'Solaris',
    'SpaceInvaders',
    'StarGunner',
    'Surround',
    'Tennis',
    'TimePilot',
    'Tutankham',
    'UpNDown',
    'Venture',
    'VideoPinball',
    'WizardOfWor',
    'YarsRevenge',
    'Zaxxon',
]


# Atari 57 - overestimation 6 - atari 5
ATARI_46 = [
    'Amidar',
    'Assault',
    'Asteroids',
    'Atlantis',
    'BankHeist',
    'BeamRider',
    'Berzerk',
    'Bowling',
    'Boxing',
    'Breakout',
    'Centipede',
    'ChopperCommand',
    'CrazyClimber',
    'Defender',
    'DemonAttack',
    'Enduro',
    'FishingDerby',
    'Freeway',
    'Frostbite',
    'Gopher',
    'Gravitar',
    'Hero',
    'IceHockey',
    'Jamesbond',
    'Kangaroo',
    'Krull',
    'KungFuMaster',
    'MontezumaRevenge',
    'MsPacman',
    'Pitfall',
    'Pong',
    'PrivateEye',
    'Riverraid',
    'RoadRunner',
    'Robotank',
    'Skiing',
    'Solaris',
    'StarGunner',
    'Surround',
    'Tennis',
    'TimePilot',
    'Tutankham',
    'UpNDown',
    'Venture',
    'VideoPinball',
    'YarsRevenge',
]

ATARI_5 = ['BattleZone', 'DoubleDunk', 'NameThisGame', 'Phoenix', 'Qbert']
OTHER_ATARI_5 = ['Amidar', 'Bowling', 'Frostbite', 'KungFuMaster', 'Riverraid']
ATARI_5_VAL = ['BankHeist', 'VideoPinball', 'Assault', 'MsPacman', 'YarsRevenge']
ATARI_10 = ATARI_5 + OTHER_ATARI_5

ATARI_OTHER_47 = [
    'Alien',
    'Assault',
    'Asterix',
    'Asteroids',
    'Atlantis',
    'BankHeist',
    'BeamRider',
    'Berzerk',
    'Boxing',
    'Breakout',
    'Centipede',
    'ChopperCommand',
    'CrazyClimber',
    'Defender',
    'DemonAttack',
    'Enduro',
    'FishingDerby',
    'Freeway',
    'Gopher',
    'Gravitar',
    'Hero',
    'IceHockey',
    'Jamesbond',
    'Kangaroo',
    'Krull',
    'MontezumaRevenge',
    'MsPacman',
    'Pitfall',
    'Pong',
    'PrivateEye',
    'RoadRunner',
    'Robotank',
    'Seaquest',
    'Skiing',
    'Solaris',
    'SpaceInvaders',
    'StarGunner',
    'Surround',
    'Tennis',
    'TimePilot',
    'Tutankham',
    'UpNDown',
    'Venture',
    'VideoPinball',
    'WizardOfWor',
    'YarsRevenge',
    'Zaxxon',
]

Overestimation_6 = ['Alien', 'Asterix', 'Seaquest', 'SpaceInvaders', 'WizardOfWor', 'Zaxxon'] 

Overestimation_11 = ATARI_5 + Overestimation_6

ATARI_100K = [
    'Alien',
    'Amidar',
    'Assault',
    'Asterix',
    'BankHeist',
    'BattleZone',
    'Boxing',
    'Breakout',
    'ChopperCommand',
    'CrazyClimber',
    'DemonAttack',
    'Freeway',
    'Frostbite',
    'Gopher',
    'Hero',
    'Jamesbond',
    'Kangaroo',
    'Krull',
    'KungFuMaster',
    'MsPacman',
    'Pong',
    'PrivateEye',
    'Qbert',
    'RoadRunner',
    'Seaquest',
    'UpNDown',
]